//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LajiPwd {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resource {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resource() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LajiPwd.Resource", typeof(Resource).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
		/// </summary>
		internal static System.Drawing.Icon icon {
			get {
				object obj = ResourceManager.GetObject("icon", resourceCulture);
				return ((System.Drawing.Icon)(obj));
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to INSERT INTO `password` 
		///    (`id`, `title`, `remark`, `account`, `password`, `create`, `update`, `delete`)
		///VALUES
		///    (?, ?, ?, ?, ?, ?, ?, ?).
		/// </summary>
		internal static string init_magic {
			get {
				return ResourceManager.GetString("init_magic", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to CREATE TABLE `password` (
		///    `id`        INTEGER      PRIMARY KEY AUTOINCREMENT,
		///    `title`     VARCHAR(255) NOT NULL,
		///    `remark`    VARCHAR(255) NOT NULL,
		///    `account`   VARCHAR(255) NOT NULL,
		///    `password`  VARCHAR(255) NOT NULL,
		///    `create`    DATETIME     NOT NULL DEFAULT 0,
		///    `update`    DATETIME     NOT NULL DEFAULT 0,
		///    `delete`    DATETIME     NOT NULL DEFAULT 0
		///);
		///.
		/// </summary>
		internal static string table_ddl {
			get {
				return ResourceManager.GetString("table_ddl", resourceCulture);
			}
		}
	}
}
